/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import java.util.Date;
import java.util.List;
import todoApp.controler.ProjectControler;
import todoApp.controler.TaskControler;
import todoApp.model.Project;
import todoApp.model.Task;
import todoApp.view.MainScreen;

public class App {

    public static void main(String[] args) {
        
        MainScreen mainScreen = new MainScreen();
        mainScreen.setVisible(true);
        
    }
}
